;;; corkey-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from corkey.el

(register-definition-prefixes "corkey" '("cor"))


;;; Generated autoloads from corkey-scratch.el

(register-definition-prefixes "corkey-scratch" '("corkey/"))

;;; End of scraped data

(provide 'corkey-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; corkey-autoloads.el ends here
